### PR TITLE
rewritten api that doesn't depend on open tracing implementations

### PR DESCRIPTION
**Pull request by sfriberg**
Wanted to get your feedback, and see if this would make sense.

### CODE REVIEW

**Comment by thegreystone** [comment]
A lot of it makes sense! That said, I'd rather avoid the code that requires us to looks at implementation specific keys. How about waiting a bit for OpenTracing 0.32.0 and utilizing the API additions there? I'd also prefer having a clean split between the API wrapping and the event emissions, perhaps we can find a way to make that cleaner and still save an object creation. Slf is an extra dependency (for something that should only log anything if it's terribly broken), but it's a tiny one, so probably fine. 

How about we start off in the opentracing-0.32.0 branch, and massage it into something superb?

**Comment by sfriberg** [comment]
well, those are a bit more standard and stable than having a hard version dependency ;)

benefit of sl4j is that is pretty much standard all over the place

Yes, was considering if we wanted them separate or not, but decided it was best to minimize the allocation. Will often be on the critical path, specially scopes.

**Comment by thegreystone** [comment]
Well, the difference will be a dependency on 'opentracing-api', version: '0.31.0' vs 'opentracing-api', version: '0.32.0'. Also, we get more efficient code. 0.32.0 is on its way.

**Comment by sfriberg** [comment]
@thegreystone Update things so it supports parent span now as well nicely 

should we make this into the 0.32.0 branch?

**Comment by thegreystone** [comment]
Staffan has a new PR coming.

**Pull request closed without merging**
